#!/usr/bin/env python3
"""
Emit the standard plugin badge block, and splice it into README.md (DEC-078).

WHY
    The e2e suite is the strongest quality claim these plugins have — a nested
    real A0, a real browser, a seam-off red-proof that fails the build if the
    scenarios could pass without the plugin installed. None of that was visible
    to anyone reading the README: badge coverage across the fleet was 1 badge,
    0 badges, 0 badges, 1 badge and 5 (the devkit itself).

WHAT IS AND ISN'T CLAIMED
    Every badge here is backed by something a reader can click and verify:
    workflow status comes from the live Actions badge, the licence from the repo,
    the release from the tag list. The one badge that is not GitHub-generated
    ("BDD e2e") is a static label pointing at the feature directory, so a reader
    lands on the actual scenarios. No invented percentages, no "100% coverage".

Usage:
    readme-badges.py --repo owner/name --plugin chat_comments [--apply README.md]
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

START = "<!-- BADGES:START (generated by the devkit — `make badges`) -->"
END = "<!-- BADGES:END -->"


def build(repo: str, workflow: str, features_path: str) -> str:
    base = f"https://github.com/{repo}"
    rows = [
        f"[![plugin-e2e]({base}/actions/workflows/{workflow}/badge.svg?branch=main)]"
        f"({base}/actions/workflows/{workflow})",
        f"[![BDD scenarios](https://img.shields.io/badge/tests-BDD%20e2e-brightgreen)]"
        f"({base}/tree/main/{features_path})",
        f"[![Release](https://img.shields.io/github/v/tag/{repo}?label=release&sort=semver)]"
        f"({base}/tags)",
        f"[![License: Apache-2.0](https://img.shields.io/badge/License-Apache_2.0-blue.svg)]"
        f"({base}/blob/main/LICENSE)",
        f"[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)]"
        f"({base}/blob/main/CONTRIBUTING.md)",
    ]
    return "\n".join([START, "", " ".join(rows), "", END])


def apply(readme: Path, block: str) -> str:
    text = readme.read_text(encoding="utf-8")
    if START in text and END in text:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S
        )
    # First insert: place directly under the H1 so it is the first thing seen.
    lines = text.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[: i + 1] + ["", block] + lines[i + 1 :])
    return block + "\n\n" + text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True, help="owner/name")
    ap.add_argument("--plugin", required=True)
    ap.add_argument("--workflow", default="plugin-e2e.yml")
    ap.add_argument("--features", default="tests/e2e/features")
    ap.add_argument("--apply", type=Path, help="README.md to splice into")
    args = ap.parse_args()

    block = build(args.repo, args.workflow, args.features)
    if args.apply:
        args.apply.write_text(apply(args.apply, block), encoding="utf-8")
        print(f"[readme-badges] spliced badge block into {args.apply}")
    else:
        print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
